from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Literal
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict


class UnifiedEventType(str, Enum):
    """
    Unified event categorization (Enum) to match the LLD definition.
    Example values are aligned with the design documents.
    """
    STORAGE_ACCESS = "STORAGE_ACCESS"
    POLICY_CHANGE = "POLICY_CHANGE"


class NormalizedEvent(BaseModel):
    """
    Unified Internal Schema:
    A normalized representation of a cloud event used by all downstream components.

    This schema preserves traceability by keeping the original raw payload.
    """

    model_config = ConfigDict(extra="forbid")

    event_uuid: UUID = Field(
        ...,
        description="A unique identifier generated by the system for every event.",
    )
    cloud_provider: Literal["AWS", "AZURE", "GCP"] = Field(
        ...,
        description="The source cloud provider.",
    )
    unified_event_type: UnifiedEventType = Field(
        ...,
        description="Unified categorization of the event type.",
    )
    timestamp_utc: datetime = Field(
        ...,
        description="Event time normalized to UTC.",
    )
    resource_id: str = Field(
        ...,
        min_length=1,
        description="Cloud resource identifier (e.g., ARN / Azure Resource ID).",
    )
    raw_payload: Dict[str, Any] = Field(
        ...,
        description="Original provider-specific payload for traceability.",
    )

    @staticmethod
    def now_utc() -> datetime:
        """
        Utility method: returns current UTC time with timezone info.
        """
        return datetime.now(timezone.utc)